name: CI

on: [push]

permissions:
  contents: read

jobs:
  test_msrv:
    name: build on MSRV
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
      with:
        toolchain: 1.88.0
    # Don't use --all-features because `frost` has a higher MSRV and it's non-default.
    # Also don't run tests because some dev-dependencies have higher MSRVs.
    - run: cargo build
  test_nightly:
    name: test on nightly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
      with:
        toolchain: nightly
    # Update dependencies since we commit the lockfile
    - run: cargo update --verbose
    - run: cargo test --all-features
  build_no_std:
    name: build with no_std
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
      with:
        toolchain: stable
        targets: thumbv6m-none-eabi
    - run: cargo build --no-default-features --target thumbv6m-none-eabi
